requests now generate the hmac according to version 2 of the onOffice…
onOfficeGmbH/sdk pull request #42
Opened 2022-03-08 15:11 UTC by AndrejThomsen

Now using the HMAC v2 of the onOffice-API

2022-03-08 15:15 UTC, jayay requested changes

2022-03-08 15:15 UTC, jayay commented on tests/RequestTest.php
> +		$this->assertEquals($hmac, $result['hmac']);
I would prefer comparing against some fixed string here instead of re-implementing the HMAC in the test

2022-03-08 15:15 UTC, jayay commented on src/internal/Request.php
> + * @copyright 2016, onOffice(R) Software AG
current copyright would be even nicer

2022-03-14 13:49 UTC, jayay approved these changes

2022-03-16 10:50 UTC, legionth approved these changes
Thank you for the contribution!

Basically this change looks good to me. But the DocBlock-Style seems a bit odd.
You probably have the default "onOffice-PHPStrom-Settings", you may want to change it for upcoming PRs.

Neither the less, I'll merge this, because this is just a minor issue here.

2022-03-16 10:50 UTC, merged